# lightning.pytorch==2.0.5
seed_everything: 42
trainer:
  gradient_clip_val: 5.0
  accumulate_grad_batches: 8
  num_nodes: 1
  precision: 32-true
  logger: WandbLogger
  callbacks: 
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val_loss_epoch
      patience: 5
  fast_dev_run: false
  max_epochs: 80
  max_steps: -1
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
model:
  path_name: UDTube
  model_name: bert-base-multilingual-cased
  udtube_dropout: 0.3
  encoder_dropout: 0.5
  udtube_learning_rate: 1e-3
  encoder_model_learning_rate: 5e-5
  pooling_layers: 4
data:
  train_dataset: el_gdt-ud-train.conllu
  val_dataset: el_gdt-ud-dev.conllu
  batch_size: 8
  convert_to_um: false
  reverse_edits: true
  language: el